version: "3"

services:
  server1:
    build: .
    environment:
      PORT: 8081
    ports:
      - "8081:8081"
    network_mode: host

  server2:
    build: .
    environment:
      PORT: 8082
    ports:
      - "8082:8082"
    network_mode: host
